git clone https://github.com/google/guava
git clone https://github.com/voldemort/voldemort
git clone https://github.com/roboguice/roboguice
git clone https://github.com/klinker24/Talon-for-Twitter
git clone https://github.com/google/protobuf
git clone https://github.com/facebook/facebook-android-sdk
git clone https://github.com/yusuke/twitter4j
git clone https://github.com/Wizcorp/phonegap-facebook-plugin
git clone https://github.com/antonkrasov/AndroidSocialNetworks
git clone https://github.com/googlei18n/libphonenumber
git clone https://github.com/sromku/android-simple-facebook
git clone https://github.com/lintool/twitter-tools
git clone https://github.com/draios/sysdig
git clone https://github.com/google/or-tools
git clone https://github.com/minetest/minetest

git clone https://github.com/draios/sysdig
git clone https://github.com/google/protobuf
git clone https://github.com/google/or-tools
git clone https://github.com/minetest/minetest
git clone https://github.com/google/googletest
git clone https://github.com/googlei18n/libphonenumber
git clone https://github.com/google/leveldb
git clone https://github.com/voldemort/voldemort

git clone https://github.com/ruby/ruby
git clone https://github.com/rails/rails
git clone https://github.com/Homebrew/linuxbrew
git clone https://github.com/sferik/twitter
git clone https://github.com/arsduo/koala
git clone https://github.com/google/protobuf
git clone https://github.com/voldemort/voldemort